### PR TITLE
Fixed #513

### LINKED ISSUE #513: Italics in links don't transfer to InDesign
Example: https://thetech.com/2019/05/01/zuber-postdocs-harassment-response

### PR DESCRIPTION
**Pull request by tareqdandachi**

### CODE REVIEW

**Comment by isundaylee** [comment]
Why are there 164 commits in this PR?

**Comment by tareqdandachi** [comment]
I accidentally pushed an API key (the test google drive ruby api key) two commits ago, so I followed the GitHub steps to remove sensitive data. I am dumb and sad.
  

  
  

  
  
>

**Comment by isundaylee** [comment]
@tareqdandachi Ah interesting. No worries. But shouldn't that only go back 2 commits instead of 164?

**Comment by isundaylee** [comment]
@tareqdandachi By the way it might be actually easier to revoke and regenerate the API key if it's not yet used in production anywhere :)

**Comment by tareqdandachi** [comment]
I revoked them, the file shouldn't have been in this branch anyways, I
accidentally left it in the staging area :(, which is why I tried scrubbing
it so that we don't face issues of its origin in the future. If you would
prefer, I could delete this branch and recreate it, it was like 2 changes
only.

**Comment by isundaylee** [comment]
@tareqdandachi If you already revoked the key I don't think it's necessary to scrub history at all. Just doing another commit removing the key should suffice? Let me know what you think.

**Pull request closed without merging**
